transfering afile

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -13,3 +13,9 @@ else
   fi;
 fi;
 
+if [ $? -eq 0 ]
+then
+	echo "FILE WAS TRANSFERRED SUCCESSFULLY"
+else
+	echo "FILE TRANSFER FAILED"
+fi;
